# Para Python
- name: Run Linter
  run: |
    find . -name "*.py" -exec flake8 {} + || true
    echo "Linted all the python files successfully"

# Para JS
- name: Run Linter
  run: |
    find ./server/database -name "*.js" -exec jshint {} + || true
    echo "Linted all the js files successfully"
